### ISSUE TITLE
All requests to yandex market True

### ISSUE THREAD

**Issue by rootadmin7** [snooppr/snoop#8]
All requests to yandex market True
![image](https://user-images.githubusercontent.com/43704227/74620916-c9a58680-5160-11ea-8067-95ade6482ae1.png)
You must exclude it from the search or modify it

**Comment by snooppr** [comment]
1. YandexCollection moved to gray list

2. YandexMarket unfortunately works on some client IP addresses as false positive.
In the ru zone, the search is correct. I also checked the search through the VPN (Europe). The search also runs correctly.

In order to minimize search errors, change your IP more often.

![2](https://user-images.githubusercontent.com/61022210/74640963-89a2cb80-5181-11ea-9a1b-189a120259fc.png)

**Comment by rootadmin7** [comment]
145 / 10000
АНГЛИЙСКИЙ
Перевести вGoogleBing
The fact that the script reports that the search is correct when Yandex offers a non-existent account as the correct page, in fact there is no account there

**Comment by snooppr** [comment]
I repeat. This is a problem due to your IP address.

On the screen you see that a nonexistent account was not found
https://github.com/snooppr/snoop/issues/8#issuecomment-586899436
