### ISSUE TITLE
Full Version Purchase US

### ISSUE THREAD

**Issue by J775w** [snooppr/snoop#85]
Hi, I am very impressed with your project and would like to acquire the full version, but I cannot find on the page how to do so, is there any way I can get it? Thanks, all the best.

**Comment by snooppr** [comment]
Hello. 
 Thank you for your kind feedback.  
 To purchase Snoop Project full version:
`snoop_cli --donate`
This is reported in the documentation, readme, license and finally in the software itself:
`snoop_cli --help`

If you have any personal questions, please do not hesitate to write to me by email, I will be happy to help.  I'll close this because...  answered the question.
