### ISSUE TITLE
Problems loading at launch-

### ISSUE THREAD

**Issue by PhyLoop** [snooppr/snoop#86]
Hello mate, im trying to load up Snoop using desktop - Kali - but im struggling to get it launched properly  and i recive this error code, any ideas how i can get it up and running? 
It looks top notch and im looking forward to using it my man

Traceback (most recent call last):
  File "/home/user/snoop/snoop.py", line 40, in <module>
    import snoopplugins
  File "/home/user/snoop/snoopplugins.py", line 39, in <module>
    import folium
ModuleNotFoundError: No module named 'folium'

**Comment by snooppr** [comment]
Hello.

 Snoop Project is custom software, which means it does not require technical skills from the user (This does not require even the installed Python from the user.), just [download](https://github.com/snooppr/snoop/releases) the ready-made assembly and use it.
![2024-01-08-08-21-54-551](https://github.com/snooppr/snoop/assets/61022210/7d5c80bf-3e4d-4b09-97c9-e24780e4be06)

---------

If you want to build Snoop Project yourself from source code, then simply follow the instructions: "[Self-build software from source](https://github.com/snooppr/snoop/blob/master/README.en.md)".

The error you receive says that you are trying to build Snoop Project from source code without following the instructions.

If your problem is not solved let me know, I will close this as soon as possible.
